export default function Head() {
  return (
    <>
      <title>Default Title</title>
      <meta name="description" content={"Generated by create next app"} />
      <link rel="icon" href="/favicon.ico" />
      <link rel="apple-touch-icon" href="/logo192.png" />
    </>
  )
}
